### ISSUE TITLE
What is the ENABLE_DRAFTS option in CMake?

### ISSUE THREAD

**Issue by KrishnaPG** [zeromq/zebra#35]
Can someone please explain what is the `ENABLE_DRAFTS` option in the cmake file?

I tried to turn-it off and build the project and encountered this below error:

```
error LNK2019: unresolved external symbol _xrap_msg_destroy referenced in function _zeb_response_destroy
```

Upon closer inspection the file `src/xrap_msg.c` and few others are added only in the `ENABLE_DRAFTS` mode. Without that option, none of the xrap\* files are present in the project.

I thought xrap is the key to this functionality - how come it became optional and went into `drafts only` mode? Without the XRAP what is the expected behavior?

**Comment by sappo** [comment]
Hi, all of zebras APIs are currently DRAFT thus if you disable draft mode
nothing should be compiled which causes weird things to happen. I will
eventually promote the APIs to stable when I have it running in production
for a while.

Am 27.08.2016 15:47 schrieb "Gopalakrishna Palem" <notifications@github.com
